---

# Cassandra Setup

# - name: Adds dcos-cassandra
#   shell: /home/vagrant/dcos-cli/bin/dcos package install cassandra --yes
#   register: setup_cassandra
#   until: setup_cassandra|success

- name: Copy Cassandra init.cql
  copy: src=cass-init.cql dest=/tmp/cass-init.cql
  register: copy_cass_init
  when: setup_cassandra|success

# TODO
# - name: Execute cass-init.cql
#   # shell: docker run -ti cassandra:2.2.5 cqlsh node-0.cassandra.mesos -f /tmp/cass-init.cql
#   register: exec_cass_init
#   when: copy_cass_init|success
#   until: exec_cass_init|success

# # Kafka Setup

# - name: Adds dcos-kafka
#   shell: /home/vagrant/dcos-cli/bin/dcos package install kafka --yes
#   ignore_errors: True

# - name: Adds kafka-brokers
#   shell: /home/vagrant/dcos-cli/bin/dcos kafka broker add 0..2 --port 9092
#   register: brokers_added
#   until: brokers_added|success

# - name: Starts kafka-brokers
#   shell: /home/vagrant/dcos-cli/bin/dcos kafka broker start 0..2
#   register: brokers_started
#   when: brokers_added|success
#   until: brokers_started|success

# - name: Setup Kafka topic
#   shell: /home/vagrant/dcos-cli/bin/dcos kafka topic add tweets --replicas 3 --partitions 10
#   register: topic_setup
#   when: brokers_started|success
#   until: topic_setup|success

# # Spark Setup

# - name: Copies dcos-spark config
#   copy: src=spark-options.json dest=/tmp/spark-options.json

# - name: Adds dcos-spark
#   shell: /home/vagrant/dcos-cli/bin/dcos package install spark --yes
#   ignore_errors: True
