---
stackName: "dcos-smack"
keyName: "smack-test"
publicSlaveInstanceCount: "1"
publicSlaveInstanceType: "m3.large"
slaveInstanceCount: "5"
slaveInstanceType: "m3.large"
bucket: "smack-bucket-1"
oauthEnabled: "false"
adminLocation: "0.0.0.0/32"
